POST https://mobileapps.ardanradio.com/api/user/registerToken
Content-Type: application/json
Accept: application/json

 {"id_user": 14, "name": "Yudi Ripayansah", "token": "f3BlKa-7RqS4Nkz17iiZmd:APA91bGIt1gYYJrfozEiroI3EMLsnaqKxvmsdDra3UCS9aGtu5KhIEIzpIpVoaqvnmVvgkqnse1yTq9rgDXwb3e32AZW1TKPJYZdvKbB0gyHPPDSQf3t6go7NkABxDi2jXu5H28aKNSw"}