const Icons = {
  search: require('../assets/images/svg/icon-search.png'),
  searchDark: require('../assets/images/svg/icon-search-dark.png'),
  back: require('../assets/images/svg/icon-back.png'),
  bookmark: require('../assets/images/svg/icon-bookmark.png'),
  chevronRight: require('../assets/images/svg/icon-chevron-right.png'),
  comment: require('../assets/images/svg/icon-comment.png'),
  flame: require('../assets/images/svg/icon-flame.png'),
  love: require('../assets/images/svg/icon-love.png'),
  notif: require('../assets/images/svg/icon-notif.png'),
  notifDark: require('../assets/images/svg/icon-notif-dark.png'),
  pause: require('../assets/images/svg/icon-pause.png'),
  share: require('../assets/images/svg/icon-share.png'),
  user: require('../assets/images/svg/icon-user.png'),
  menuContent: require('../assets/images/menu/content.png'),
  menuEvents: require('../assets/images/menu/event.png'),
  menuNews: require('../assets/images/menu/news.png'),
  menuSocial: require('../assets/images/menu/social.png'),
  navHome: require('../assets/images/svg/nav-home.png'),
  navHomeActive: require('../assets/images/svg/nav-home-active.png'),
  navPause: require('../assets/images/svg/nav-pause.png'),
  navProfile: require('../assets/images/svg/nav-profile.png'),
  navProfileActive: require('../assets/images/svg/nav-profile-active.png'),
  navRadio: require('../assets/images/svg/nav-radio.png'),
}
export default Icons